[package]
name = "orchid"
version = "0.1.1"
exclude = ["docs/"]
entrypoint = "lib.typ"
authors = ["Jassiel Ovando <@jassielof>"]
repository = "https://github.com/jassielof/typst-packages"
license = "MIT"
description = "ORCID identifier tooling inspired from the LaTeX package ORCID link."
